"""add name to sticker set model

Revision ID: 2161585c21b1
Revises: ca9bde7445d2
Create Date: 2022-11-12 14:53:51.046122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2161585c21b1'
down_revision = 'ca9bde7445d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sticker', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('sticker', sa.Column('file_unique_id', sa.String(length=512), nullable=False))
    op.add_column('sticker', sa.Column('image_hash', sa.String(length=256), nullable=False))
    op.add_column('sticker_set', sa.Column('name', sa.String(length=256), nullable=False))
    op.create_unique_constraint(None, 'sticker_set', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sticker_set', type_='unique')
    op.drop_column('sticker_set', 'name')
    op.drop_column('sticker', 'image_hash')
    op.drop_column('sticker', 'file_unique_id')
    op.drop_column('sticker', 'created_at')
    # ### end Alembic commands ###
