"""add file_id to sticker model

Revision ID: 49aa5ea65f7a
Revises: 2161585c21b1
Create Date: 2022-11-12 15:02:53.794973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49aa5ea65f7a'
down_revision = '2161585c21b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sticker', sa.Column('file_id', sa.String(length=512), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sticker', 'file_id')
    # ### end Alembic commands ###
